# WinBtrfs: VS2019 current master, VS2015 still/v1.4 "official" minimal, plus VS2010 as "unsupported" minimal.
# https://docs.microsoft.com/en-us/cpp/build/how-to-modify-the-target-framework-and-platform-toolset?view=vs-2019
#   2015 = v140, 2017 = v141, 2019 = v142, ABI-backwards-compatible.
image:
#   - Visual Studio 2015
# 
  - Visual Studio 2017
    # Slow to start: on demand :-|
# 
  - Visual Studio 2019
    # Slow to start: on demand :-|
#   - Visual Studio 2019 Preview

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: amQ18PhcGpzi95VrjdE94A==

version: VS201_.btrfs.appveyor.{build}
skip_branch_with_pr: true
skip_tags: true
clone_depth: 5
clone_folder: C:\projects\btrfs

# default = Debug|Win32, (the first one in sln/proj files!?)
# platform:
#   - Win32
#   - x64
# configuration:
#   - Debug
#   - Release

# init:
# Guess try:
# 2015, 2017 and 2019: Not set :-|
#   - echo %VCTargetsPath%
#   - set
# 2015: Looks good :-)
# 2017 and 2019: directory does not exist.
#   - dir C:\WinDDK
#   - dir C:\WinDDK /s
# '/usr/bin/sed'
#   - which sed
#   - sed --help
# later!?
#   - msbuild -version

build:
  project: btrfs.sln
#   verbosity: normal
#   verbosity: minimal
  verbosity: quiet

# btrfs.sln
# +
# btrfs.vcxproj
# mkbtrfs.vcxproj
# shellbtrfs.vcxproj
# ubtrfs.vcxproj

after_build:
#   - dir /s
  - cd Debug\x86
#   - if %Configuration%_%Platform%==Debug_Win32  cd Debug\x86
#   - if %Configuration%_%Platform%==Debug_x64  cd Debug\x64
#   - if %Configuration%_%Platform%==Release_Win32  cd x86
#   - if %Configuration%_%Platform%==Release_x64  cd x64
  - appveyor PushArtifact btrfs.sys

test: off

for:
-
  matrix:
    only:
      - image: Visual Studio 2015

  build:
    project: btrfs_noCpp17.sln
    verbosity: quiet

  before_build:
 # "std::string_view was introduced in C++17, which is only supported from VS 2017 15.0(+)."
 # Then VS 2015 can't build shellbtrfs!
 # (How to edit the files _from command line_ to remove it? Or select targets from AppV?)
 # Is it possible to revert only Shell to its "v1.1"(!?)?
#
# Required: 
    - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v140<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0, 10, 8.0, 8.
 # 8.1 found, but error: shellbtrfs, 'error C2011: '_FSCTL_GET_INTEGRITY_INFORMATION_BUFFER': 'struct' type redefinition'! + no string_view support + 1 last error.
 # 10.0.18362.0 found, but error: shellbtrfs, no string_view support + 1 last error.
    - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
 # 'C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.OS.props(250,11): error MSB4086: A numeric comparison was attempted on "$(SUBSYSTEM_NATVER)" that evaluates to "" instead of a number, in condition "'$(MIDL_TARGET)' == '$(MIDL_TARGET_VISTA)' AND $(SUBSYSTEM_NATVER) < 6.00". [C:\projects\btrfs\btrfs.vcxproj]'
# Caused by VS2015/[W]SDK itself, or AppVeyor-specific?
#
# 7600.16385.1.
#     - dir C:\WinDDK\
# v7.0, v7.0A, v7.1, v7.1A, v8.0, v8.0A, v8.1, v8.1A, v10.0A
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\"
# 10.
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\"
# 8.0, 8.1 and 10.
#     - dir "C:\Program Files (x86)\Windows Kits\"
#
## RDP: Check/try upgrade of VS/SDKs.
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
-
  matrix:
    only:
      - image: Visual Studio 2017

##   environment:
##     additional_flags: /permissive-

  before_build:
##     - set CFLAGS=%additional_flags%
##     - set CXXFLAGS=%additional_flags%
# TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v140<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0, 10, 8.0, 8.
 # 8.1 found, but error: shellbtrfs, 'error C2011: '_FSCTL_GET_INTEGRITY_INFORMATION_BUFFER': 'struct' type redefinition'! + no string_view support.
 # 10.0.18362.0 found, but error: shellbtrfs, no string_view support.
# v140:     - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
##    - for %%p in (*.vcxproj) do  sed -i "s|<LanguageStandard>stdcpplatest</LanguageStandard>|<AdditionalOptions>|std:c++latest %(AdditionalOptions)</AdditionalOptions>|g" %%p
#
# Required: 
    - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v141<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0, 10, 8.0, 8.
 # 8.1 found, but error: shellbtrfs, 'error C2011: '_FSCTL_GET_INTEGRITY_INFORMATION_BUFFER': 'struct' type redefinition'!
      # 10.0.18362.0 found: success :-)
# v141: 
    - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
# CfCommit:    - sed -i "s|<LanguageStandard>stdcpplatest<|<LanguageStandard>stdcpp17<|g" shellbtrfs.vcxproj
#
#   - ps: (Get-Content ubtrfs.vcxproj) | Foreach-Object {$_ -replace "v141", "v140"} | Set-Content ubtrfs.vcxproj
#   - ps: (Get-Content ubtrfs.vcxproj) | Foreach-Object {$_ -replace "<WindowsTargetPlatformVersion>10.0.18362.0<", "<WindowsTargetPlatformVersion>8.1<"} | Set-Content ubtrfs.vcxproj
#
# v7.0A, v7.1A, v8.0, v8.0A, v8.1, v8.1A, v10.0A
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\"
# 10.
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\"
# 8.0, 8.1 and 10.
#     - dir "C:\Program Files (x86)\Windows Kits\"
#
## RDP: Try conformance option.
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
-
  matrix:
    only:
      - image: Visual Studio 2019

##   environment:
##     additional_flags: /permissive-

  before_build:
##     - set CFLAGS=%additional_flags%
##     - set CXXFLAGS=%additional_flags%
# TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v140<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0, 10, 8.1, 8.0, 8.
 # 10.0.18362.0, 10.0.17763.0 found, but error: shellbtrfs, no string_view support.
# CfCommit: v140:     - sed -i "s|<WindowsTargetPlatformVersion>8\.1<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" mkbtrfs.vcxproj
# v140:     - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
 # does not replace...    - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>(8\.1|10\.0)<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
#
 # 'error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found.'
# TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v141<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   10.0, ²8.1.
      # ²10.0.18362.0 found :-|
## CfCommit: v141:     - sed -i "s|<WindowsTargetPlatformVersion>8\.1<|<WindowsTargetPlatformVersion>10.0<|g" mkbtrfs.vcxproj
## v141:     - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>8<|g" %%p
#
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 8.1, 8.0, 8.
      # 10.0.18362.0, 10.0.17763.0, 10.0, 10 found: success :-)
# CfCommit: v142:     - sed -i "s|<WindowsTargetPlatformVersion>8\.1<|<WindowsTargetPlatformVersion>10.0<|g" mkbtrfs.vcxproj
      # And this one too. Optional, but be consistent.
 # btrfs: 'error : An SDK corresponding to WDK version '10.0.18362.0' was not found.'
#     - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0\.18362\.0<|<WindowsTargetPlatformVersion>10.0<|g" %%p
# CfCommit:    - sed -i "s|<LanguageStandard>stdcpplatest<|<LanguageStandard>stdcpp17<|g" shellbtrfs.vcxproj
#
# v7.1A, v10.0A
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\"
# 10.
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\"
# 8.1 and 10.
#     - dir "C:\Program Files (x86)\Windows Kits\"
#
# TestOnly: to check installing missing v141 component. It works :-)
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
## RDP: Try conformance option.
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
-
  matrix:
    only:
# VS2019P: "obsolete" :-<
      - image: Visual Studio 2019 Preview

  before_build:
## TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v140<|g" %%p
#
## TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v141<|g" %%p
#
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0.18362.0, 10.0, 10, 8.0, 8.
 # 8.1 found, but 2 errors...
 #  btrfs: 'error MSB4062: The "ValidateNTTargetVersion" task could not be loaded from the assembly C:\Program Files (x86)\Windows Kits\10\build\bin\Microsoft.DriverKit.Build.Tasks.16.0.dll.'
 #  ubtrfs: 'fatal error C1083: Cannot open include file: 'ata.h': No such file or directory'
 # 10.0.17763.0 found, but error: btrfs: 'error MSB4062: The "ValidateNTTargetVersion" task could not be loaded from the assembly C:\Program Files (x86)\Windows Kits\10\build\bin\Microsoft.DriverKit.Build.Tasks.16.0.dll.'
    - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0\.18362\.0<|<WindowsTargetPlatformVersion>10.0.17763.0<|g" %%p
#       # And this one too?!
#     - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>8.1<|g" %%p
#
# v7.0A, v7.1A, v8.0, v8.0A, v8.1, v8.1A, v10.0A
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\"
# 10.
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\"
# 8.0, 8.1 and 10.
#     - dir "C:\Program Files (x86)\Windows Kits\"
