# WinBtrfs: VS2019 current master, VS2015 still/v1.4 "official" minimal, plus VS2010 as "unsupported" minimal.
# https://docs.microsoft.com/en-us/cpp/build/how-to-modify-the-target-framework-and-platform-toolset?view=vs-2019
#   (2012 = v110;)
#   2013 = v120;
#   2015 = v140, 2017 = v141, 2019 = v142, ABI-backwards-compatible.
image:
  - Visual Studio 2019
    # (A bit = "30s") Slow to start: on demand :-|
#   - Visual Studio 2013
#   - Visual Studio 2015
    # Fast to start: pre-heated :->
#   - Visual Studio 2015 Preview
# 
  - Visual Studio 2017
    # Slow to start: on demand :-|
#   - Visual Studio 2017 Preview
# 
    # Slow to start: on demand :-|
#   - Visual Studio 2019 Preview

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: amQ18PhcGpzi95VrjdE94A==

version: VS201_.btrfs.appveyor.{build}
skip_branch_with_pr: true
skip_tags: true
clone_depth: 5
clone_folder: C:\projects\btrfs

# default = Debug|Win32, (the first one in sln/proj files!?)
# platform:
#   - Win32
#   - x64
# configuration:
#   - Debug
#   - Release

# 
init:
  - ver
# Guess try:
# 2015, 2017 and 2019: Not set :-|
#   - echo %VCTargetsPath%
#   - set
# 2015: Looks good :-)
# 2017 and 2019: directory does not exist.
#   - dir C:\WinDDK
#   - dir C:\WinDDK /s
# '/usr/bin/sed'
#   - which sed
#   - sed --help
# later!?
# 
  - msbuild -version
# 
  - where msbuild

build:
  project: btrfs.sln
#   verbosity: normal
#   verbosity: minimal
  verbosity: quiet

# btrfs.sln
# +
# btrfs.vcxproj
# mkbtrfs.vcxproj
# shellbtrfs.vcxproj
# ubtrfs.vcxproj

after_build:
#   - dir /s
  - cd Debug\x86
#   - if %Configuration%_%Platform%==Debug_Win32  cd Debug\x86
#   - if %Configuration%_%Platform%==Debug_x64  cd Debug\x64
#   - if %Configuration%_%Platform%==Release_Win32  cd x86
#   - if %Configuration%_%Platform%==Release_x64  cd x64
#
#   - dir
#   - appveyor PushArtifact btrfs.sys
#   - appveyor PushArtifact mkbtrfs.exe
#   - appveyor PushArtifact shellbtrfs.dll
#   - appveyor PushArtifact ubtrfs.dll
 # ''7zr' is not recognized as an internal or external command, operable program or batch file.'
  - 7z a -mx WinBtrfs.7z *.dll *.exe *.sys
# + pdb:   - 7z a -mx WinBtrfs.7z *.dll *.exe *.pdb *.sys
  - appveyor PushArtifact WinBtrfs.7z

test: off

for:
-
  matrix:
    only:
        # (Windows 6.3.9600, msbuild 12.0.40629.0).
        # (C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe).
      - image: Visual Studio 2013

# When without 'string' commit.
  build:
    project: btrfs_noCpp17.sln
    verbosity: quiet

  before_build:
 # 'error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found.'
 # WKMD8.1 found, but many errors...
 #  btrfs: 'error C2065: 'FILE_DISPOSITION_INFORMATION_EX' : undeclared identifier' and more!
# Required: 
    - sed -i "s|<PlatformToolset>WindowsKernelModeDriver10\.0<|<PlatformToolset>WindowsKernelModeDriver8.1<|g" btrfs.vcxproj
 # 'error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found.'
 # v120 found, but errors:
 #  shellbtrfs, 'error C2011: '_FSCTL_GET_INTEGRITY_INFORMATION_BUFFER': 'struct' type redefinition' and more + no string_view support!
 #  ubtrfs: 'fatal error C1083: Cannot open include file: 'ata.h': No such file or directory' (As VS2019P used to have.)
# Required: 
    - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v120<|g" %%p
#
## RDP: Check/try upgrade of VS/SDKs.
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
-
  matrix:
    only:
        # (Windows 6.3.9600, msbuild 14.0.25420.1).
        # (C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe).
      - image: Visual Studio 2015
        # "obsolete" :-| (Windows 6.3.9600, msbuild 14.0.25420.1).
        # (C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe).
## 
      - image: Visual Studio 2015 Preview

# When without 'string' commit.
  build:
    project: btrfs_noCpp17.sln
    verbosity: quiet

  before_build:
 # "std::string_view was introduced in C++17, which is only supported from VS 2017 15.0(+)."
 # Then VS 2015 can't build shellbtrfs!
 # (How to edit the files _from command line_ to remove it? Or select targets from AppV?)
 # Is it possible to revert only Shell to its "v1.1"(!?)?
#
# Required: 
    - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v140<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0, 10, 8.0, 8.
 # 8.1 found, but error: shellbtrfs, 'error C2011: '_FSCTL_GET_INTEGRITY_INFORMATION_BUFFER': 'struct' type redefinition'! + no string_view support + 1 last error.
 # 10.0.18362.0 found, but error: shellbtrfs, no string_view support + 1 last error.
    - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
 # 'C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.OS.props(250,11): error MSB4086: A numeric comparison was attempted on "$(SUBSYSTEM_NATVER)" that evaluates to "" instead of a number, in condition "'$(MIDL_TARGET)' == '$(MIDL_TARGET_VISTA)' AND $(SUBSYSTEM_NATVER) < 6.00". [C:\projects\btrfs\btrfs.vcxproj]'
# Caused by VS2015/[W]SDK itself, or AppVeyor-specific?
#
# 7600.16385.1.
#     - dir C:\WinDDK\
# v7.0, v7.0A, v7.1, v7.1A, v8.0, v8.0A, v8.1, v8.1A, v10.0A
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\"
# 10.
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\"
# 8.0, 8.1, 10 and NETFXSDK.
#     - dir "C:\Program Files (x86)\Windows Kits\"
#
## RDP: Check/try upgrade of VS/SDKs.
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
-
  matrix:
    only:
        # (Windows 10.0.14393, msbuild 15.9.21.664).
        # (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe).
      - image: Visual Studio 2017

##   environment:
##     additional_flags: /permissive-

  before_build:
##     - set CFLAGS=%additional_flags%
##     - set CXXFLAGS=%additional_flags%
# TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v140<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0, 10, 8.0, 8.
 # 8.1 found, but error: shellbtrfs, 'error C2011: '_FSCTL_GET_INTEGRITY_INFORMATION_BUFFER': 'struct' type redefinition'! + no string_view support.
 # 10.0.18362.0 found, but error: shellbtrfs, no string_view support.
# v140:     - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
##    - for %%p in (*.vcxproj) do  sed -i "s|<LanguageStandard>stdcpplatest</LanguageStandard>|<AdditionalOptions>|std:c++latest %(AdditionalOptions)</AdditionalOptions>|g" %%p
#
# Required: 
    - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v141<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0, 10, 8.0, 8.
 # 8.1 found, but error: shellbtrfs, 'error C2011: '_FSCTL_GET_INTEGRITY_INFORMATION_BUFFER': 'struct' type redefinition'!
      # 10.0.18362.0 found: success :-)
    - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
# CfCommit:    - sed -i "s|<LanguageStandard>stdcpplatest<|<LanguageStandard>stdcpp17<|g" shellbtrfs.vcxproj
#
#   - ps: (Get-Content ubtrfs.vcxproj) | Foreach-Object {$_ -replace "v141", "v140"} | Set-Content ubtrfs.vcxproj
#   - ps: (Get-Content ubtrfs.vcxproj) | Foreach-Object {$_ -replace "<WindowsTargetPlatformVersion>10.0.18362.0<", "<WindowsTargetPlatformVersion>8.1<"} | Set-Content ubtrfs.vcxproj
#
# v7.0A, v7.1A, v8.0, v8.0A, v8.1, v8.1A, v10.0A
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\"
# 10.
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\"
# 8.0, 8.1, 10 and NETFXSDK.
#     - dir "C:\Program Files (x86)\Windows Kits\"
#
## RDP: Try conformance option.
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
-
  matrix:
    only:
        # "obsolete" :-< (Windows 10.0.14393, msbuild 15.9.19.36755, + 'Windows SDK version 10.0.18362.0 was not found').
        # (C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\MSBuild.exe).
## 
      - image: Visual Studio 2017 Preview

  before_build:
# Required: 
    - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v141<|g" %%p
#
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   10.0.18362.0, 10.0.17763.0.
     # 8.1 found, but too old...
     # 10.0.14393.0 found, but errors...
    - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.14393.0<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   10.0.18362.0, 10.0.17763.0, 8.1.
     # 10.0.14393.0 found, but errors...
    - sed -i "s|<WindowsTargetPlatformVersion>10\.0\.18362\.0<|<WindowsTargetPlatformVersion>10.0.14393.0<|g" btrfs.vcxproj
-
  matrix:
    only:
        # (Windows 10.0.17763.805, msbuild 16.3.1.50202).
        # (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe).
      - image: Visual Studio 2019

##   environment:
##     additional_flags: /permissive-

# v140, When without 'string' commit.
#   build:
#     project: btrfs_noCpp17.sln
#     verbosity: quiet

  before_build:
##     - set CFLAGS=%additional_flags%
##     - set CXXFLAGS=%additional_flags%
# TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v140<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0, 10, 8.0, 8.
 # 8.1 found, but error: usual... (too old!!?)
 # 10.0.18362.0, 10.0.17763.0 found, but error: shellbtrfs, no string_view support.
# CfCommit: v140:     - sed -i "s|<WindowsTargetPlatformVersion>8\.1<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" mkbtrfs.vcxproj
# v140:     - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
 # does not replace...    - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>(8\.1|10\.0)<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
#
 # 'error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found.'
# TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v141<|g" %%p
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 10.0, 10, 8.0, 8.
 # 8.1 found, but error: usual... (too old!!?)
      # 10.0.18362.0, 10.0.17763.0 found :-|
# CfCommit: v141:     - sed -i "s|<WindowsTargetPlatformVersion>8\.1<|<WindowsTargetPlatformVersion>10.0<|g" mkbtrfs.vcxproj
# v141:     - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
#
      # 'error MSB8036: The Windows SDK version NNN was not found.':
      #   (10.0.18362.1,) 8.0, 8.
 # 8.1 found, but error: usual... (too old!!?)
      # 10.0.18362.0, 10.0.17763.0, 10.0, 10 found: success :-)
# CfCommit: v142:     - sed -i "s|<WindowsTargetPlatformVersion>8\.1<|<WindowsTargetPlatformVersion>10.0<|g" mkbtrfs.vcxproj
      # And this one too. Optional, but be consistent.
 # btrfs: 'error : An SDK corresponding to WDK version '10.0.18362.0' was not found.'
#     - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0\.18362\.0<|<WindowsTargetPlatformVersion>10.0<|g" %%p
# CfCommit:    - sed -i "s|<LanguageStandard>stdcpplatest<|<LanguageStandard>stdcpp17<|g" shellbtrfs.vcxproj
#
# v7.1A, v8.1A and v10.0A
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\"
# 10.
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\"
# 8.1, 10 and NETFXSDK.
#     - dir "C:\Program Files (x86)\Windows Kits\"
#
# TestOnly: to check outdated msbuild (component). It works :-)
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
## RDP: Try conformance option.
# 
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
-
  matrix:
    only:
        # (Windows 10.0.17763.805, msbuild 16.4.0.50203).
        # (C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe).
      - image: Visual Studio 2019 Preview

  before_build:
## TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v140<|g" %%p
#
## TestOnly:     - for %%p in (*.vcxproj) do  sed -i "s|<PlatformToolset>v14.<|<PlatformToolset>v141<|g" %%p
#
      # 'error MSB8036: The Windows SDK version NNN was not found.':
# Re-Check (RDP), then merge it with VS2019 !!?
      #   (²10.0.18362.1,) ²10.0, ²10, ²8.0, ²8.
 # ²10.0.18362.0, ²10.0.17763.0, ²8.1 found, but 3 errors:
##    - for %%p in (*.vcxproj) do  sed -i "s|<WindowsTargetPlatformVersion>10\.0<|<WindowsTargetPlatformVersion>10.0.18362.0<|g" %%p
#
# v7.0A, v7.1A, v8.1A, v10.0A
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows\"
# 10.
#     - dir "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\"
# 8.1, 10 and NETFXSDK.
#     - dir "C:\Program Files (x86)\Windows Kits\"
#
# TestOnly: to check outdated msbuild (component). It works :-)
#     - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
